#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# network-manager 的托盘
nm-applet &

# polybar 的启动
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

# 边框宽度
bspc config border_width         3
# 窗口间距
bspc config window_gap           8
# 正在使用的窗口边框颜色
bspc config focused_border_color \#7FFF00
# 正常的窗口边框颜色
bspc config normal_border_color \#FFFACD

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled split_ratio=0.6
