[opener]
play = [
	{ run = 'haruna %s', desc = "Haruna", orphan = true, for = "linux" }
]
view = [
	{ run = 'loupe %s', desc = "Loupe", for = "linux" }
]

[open]
rules = [
	# Image
	{ mime = "image/*", use = [ "view" ] },
    # Vedio
    { mime = "{audio,video}/*", use = "play" },
]
