#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# polybar 的启动
${HOME}/.config/polybar/launch.sh

# network-manager 的托盘
nm-applet &

bdwdt=3
bspc config border_width         $bdwdt
bspc config window_gap           8
bspc config focused_border_color    \#7FFF00
bspc config normal_border_color     \#FFFACD
bspc config split_ratio          0.5
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a GoldenDict desktop='^10'
# bspc rule -a smplayer state=floating center=on
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled split_ratio=0.6

# 尝试一下 external_rules
# bspc config external_rules_command "${HOME}/.config/bspwm/try_e_r"

# scratchpad
# See, https://wiki.archlinux.org/index.php/Bspwm#Using_class_name
Xaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
Yaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)
bspc rule -a scratchpad sticky=on state=floating locked=on \
    rectangle=`expr $Xaxis \* 4 / 5`x`expr $Yaxis \* 3 / 5`+`expr \
            $Xaxis / 10 - $bdwdt`+`expr $Yaxis \* 2 / 5 - $bdwdt \* 2 - 1`

