#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

echo -e "One group: \n \
    window ID : ${wid},\n \
    title : $(xtitle "${wid}"),\n \
    class name : ${class},\n \
    instance name : ${instance},\n \
    intermediate consequences : ${consequences}\n\n" \
    >> /tmp/try_e_r.log

# if [ "$instance" = fontforge ] ; then
# 	title=$(xtitle "$wid")
# 	case "$title" in
# 		Layers|Tools|Warning)
# 			echo "focus=off"
# 			;;
# 	esac
# fi

# case "$class" in
# 	Lutris|Liferea)
# 		eval "$consequences"
# 		[ "$state" ] || echo "state=pseudo_tiled"
# 		;;
# esac
