#!/usr/bin/env python

help_list = '''
===============================================================
帮助：          
    加密：
        a. 对方发来公钥，我导入
        b. gpg --recipient <对方的公钥> --output <输出文件> --encrypt <待加密文件>
        c. 把 <输出文件> 发送给对方
    解密：
        a. 对方发来加密文件，是使用我的公钥 A551B8F6A13D8A90 (long key ID) 加密的
            或者对方直接使用 thunderbird + enigmail 加密的，则会得到：
                encrypted.asc 作为加密文件，Untitled 作为一个注释文件
        b. gpg --output <输出的解密文件> --decrypt <对方发来的加密文件>
        c. 输入我自己的【私钥】密码就解密成功了
        d. 打开 <输出的解密文件>，如果对方自己加密的就能看了，
            如果是 thunderbird + enigmail 则可能里面还有一个 base64，
            这不是对方的故意设置，猜测是插件自己搞的
        e. echo <base64 密文> | base64 -d
            
    git bisect:
        git bisect start <nearly-bad> <early-good>
        git bisect good
        git bisect bad

    GitHub 搜索自己评论的issue：is:issue commenter:$username
    GitHub 搜索自己发起的issue：is:issue author:$username

    打开图片：          sxiv image_name
    命令在哪个包里：    pkgfile -s xxxxxx
    解压文件：          unar filename
    查看压缩包里的文件：lsar filename
    编辑位图：          photoflare
                        gimp 待学习
    声音格式转换：      soundkonverter
    选择字体：          gtk2fontsel
    调整音量：          alsamixer
    3D 建模：           openscad
    pacman 安装日志：   vim /var/log/pacman.log
    打开 v2ray：        systemctl start v2ray.service
    翻墙：              proxychains software_name
    录屏：              simplescreenrecorder
    电子书：            calibre
    字幕打轴：          aegisub
    天文博物馆：        stellarium
    查词典：            goldendict
    屏幕键盘：          screenkey
    Hugo 测试：         hugo server -wDF
    剪辑：              kdenlive
    播放器：            smplayer
    阅读 pdf：          zathura
    阅读 pdf：          foxitreader
    浏览器：            firefox

    合并音频和视频：
        视频中没有音频：ffmpeg -i video.mp4 -i audio.wav -c:v copy -c:a aac -strict experimental output.mp4
        视频中有声音但替换掉：ffmpeg -i video.mp4 -i audio.wav -c:v copy -c:a aac -strict experimental -map 0:v:0 -map 1:a:0 output.mp4
    剪裁视频：
        ffmpeg -i input.mp4 -strict -2 -vf crop=1080:940:0:640 output.mp4
    剪辑视频：
        ffmpeg -i input.mp4 -ss 00:00:00 -t 00:00:5 -acodec aac -vcodec h264 -strict -2 output.mp4
    切割音频：
        ffmpeg -i input.mp3 -vn -acodec copy -ss 00:03:21.36 -to 00:05:30.56 output.mp3
    提取声音：
        ffmpeg -i input.mp4 -q:a 0 -map a output.mp3
    硬压字幕：
        ffmpeg -y -i input.mp4 -vf subtitles=xxx.ass output.mp4
    压制视频：
        ffmpeg -i "input.mp4" -c:v libx264 -b:v 5000k -r 24 -c:a aac -b:a 128k "output.mp4"
    提取内嵌字幕：（<n>替换成数字，0表示第0轨道的字幕，1表示第1轨道的字幕）
        ffmpeg -i input.mkv -map 0:s:<n> output.ass
    删除视频中的声音：（只有一个音轨的情况下）
        ffmpeg -i input.mp4 -c:v copy -an output.mp4

    Python Venv:
        python3.x -m venv the-name-of-venv
        source the/path/of/venv/bin/activate
        pip install xxx -i https://pypi.tuna.tsinghua.edu.cn/simple
        deactivate

    fdisk --list 查看磁盘整体情况
    du -h ./     查看当然目录所有文件大小
    du -hd1      不递归地查看（hd2 递归一次）
    df -h ./     查看当然挂载点磁盘总大小

    可以使用 sudo pacman -Qdt 来查找孤包.
    可以使用 paccache -ruk0 来清除未安装的包缓存
    可以使用 paccache -r 来清除三个版本之前的包缓存
    若 ::安装 aaa 破坏依赖 'bbb'（ccc 需要）::，可以 pacman -Rdd ccc 后再 -Syu
    可以使用 sudo pkgfile -u 来更新 pkgfile 的数据
    可以使用 sudo updatedb 来更新 locate 使用的索引数据
    可以使用 sudo journalctl --vacuum-time=2d 来清理日志文件
    如果出现了“未知信任”（unknown trust）：sudo pacman -Sy archlinux-keyring

    翻墙走 ss：
        配置：/etc/shadowsocks/config.json
        端口：1080
        打开：systemctl start shadowsocks-libev@config.service
        火狐：FoxyProxy - myh 绿色
        Discord：http_proxy=socks5://127.0.0.1:1080 https_proxy=socks5://127.0.0.1:1080 /opt/Discord/Discord --proxy-server="socks5://127.0.0.1:1080"
        ProxyChain 配置：/etc/proxychains.conf（改最后一行端口）

    翻墙走 geph：
        配置：/etc/default/geph4-client（用户名、密码）
        端口：SOCKS5 9909 / HTTP 9910
        打开：systemctl start geph4-client.service
        火狐：FoxyProxy - geph 蓝色
        Discord：http_proxy=socks5://127.0.0.1:9909 https_proxy=socks5://127.0.0.1:9909 /opt/discord/Discord --proxy-server="socks5://127.0.0.1:9909"
        ProxyChain 配置：/etc/proxychains.conf（改最后一行端口）

    翻墙走 clash：
        配置：~/.clash/config.yaml
        端口：混合端口 7890
        打开：clash
        火狐：FoxyProxy - clash 紫色
        ProxyChain 配置：/etc/proxychains.conf（改最后一行端口）

    我自己的命令：
        myhelp      我的帮助
        proxychains ~/backup/AutoBackup.sh
                    备份一切
        add_record  添加书影记录
        blog_arr    整理博客文章的文件夹组织形式
        catch_back xxx.md A1b2C3d4E5f6G7h8I9j
                    把季度嘟文精华展里面的嵌入改写成 shortcodes，生成 xxx_new.md
                    后面的是 token

    标点符号（重装系统时定义到输入法里）：
        角度：°    U+00B0    Degree Sign
        角分：′    U+2032    Prime
        角秒：″    U+2033    Double Prime
        直单：'    U+0027    Apostrophe
        直双："    U+0022    Quotation Mark
        左单：‘    U+2018    Left Single Quotation Mark
        右单：’    U+2019    Right Single Quotation Mark
        左双：“    U+201C    Left Double Quotation Mark
        右双：”    U+201D    Right Double Quotation Mark
        连字：-    U+2010    Hyphen-Minus
        短接：–    U+2013    En Dash    数字、年份之间的“至”
        长接：—    U+2014    Em Dash    插入语、补充说明
        破折：⸺    U+2E3A    Two-Em Dash    中文排版特意使用
        破折：——   U+2014*2  2 Em Dashes    中文通常使用
        省略：…    U+2026    Horizontal Ellipsis
        间隔：·    U+00B7    Middle Dot
        圆点：•    U+2022    Bullet
        黑圆：●    U+25CF    Black Circle
        宽点：・   U+30FB    Katakana Middle Dot    日语的宽点，占一个汉字宽
        来源：https://sspai.com/post/45516

    地图工具：
        高德地图：https://amap.com/
        地图画圆：https://lbs.amap.com/demo/javascript-api/example/overlayers/circle-draw-and-edit
        获取经纬：https://lbs.amap.com/demo/javascript-api/example/map/click-to-get-lnglat
===============================================================
'''

print(help_list)
