#!/usr/bin/env python

help_list = '''
===============================================================
帮助：          
    加密：
        a. 对方发来公钥，我导入
        b. gpg --recipient <对方的公钥> --output <输出文件> --encrypt <待加密文件>
        c. 把 <输出文件> 发送给对方
    解密：
        a. 对方发来加密文件，是使用我的公钥 A551B8F6A13D8A90 (long key ID) 加密的
            或者对方直接使用 thunderbird + enigmail 加密的，则会得到：
                encrypted.asc 作为加密文件，Untitled 作为一个注释文件
        b. gpg --output <输出的解密文件> --decrypt <对方发来的加密文件>
        c. 输入我自己的【私钥】密码就解密成功了
        d. 打开 <输出的解密文件>，如果对方自己加密的就能看了，
            如果是 thunderbird + enigmail 则可能里面还有一个 base64，
            这不是对方的故意设置，猜测是插件自己搞的
        e. echo <base64 密文> | base64 -d
            
    git bisect:
        git bisect start <nearly-bad> <early-good>
        git bisect good
        git bisect bad

    打开图片：          sxiv image_name
    命令在哪个包里：    pkgfile -s xxxxxx
    压缩 zip：          zip -r -FS ../xxx.zip *
    解压 zip：          7z x xxx.zip
                        unzip xxx.zip
    解压 rar：          unrar e xxx.rar
    解压 tar.gz:        tar -zxvf xxx.tar.gz
    编辑位图：          photoflare
                        gimp 待学习
    声音格式转换：      soundkonverter
    选择字体：          gtk2fontsel
    调整音量：          alsamixer
    3D 建模：           openscad
    pacman 安装日志：   vim /var/log/pacman.log
    打开 v2ray：        systemctl start v2ray.service
    翻墙：              proxychains software_name
    录屏：              simplescreenrecorder
    电子书：            calibre
    字幕打轴：          aegisub
    天文博物馆：        stellarium
    查词典：            goldendict
    屏幕键盘：          screenkey
    Hugo 测试：         hugo server -wDF
    剪辑：              kdenlive
    播放器：            smplayer
    阅读 pdf：          zathura
    阅读 pdf：          foxitreader
    浏览器：            firefox

    合并音频和视频：
        视频中没有音频：ffmpeg -i video.mp4 -i audio.wav -c:v copy -c:a aac -strict experimental output.mp4
        视频中有声音但替换掉：ffmpeg -i video.mp4 -i audio.wav -c:v copy -c:a aac -strict experimental -map 0:v:0 -map 1:a:0 output.mp4
    剪裁视频：
        ffmpeg -i input.mp4 -strict -2 -vf crop=1080:940:0:640 output.mp4
    剪辑视频：
        ffmpeg -i input.mp4 -ss 00:00:00 -t 00:00:5 -acodec aac -vcodec h264 -strict -2 output.mp4
    提取声音：
        ffmpeg -i input.mp4 -q:a 0 -map a output.mp3
    硬压字幕：
        ffmpeg -y -i input.mp4 -vf subtitles=xxx.ass output.mp4

    Python Venv:
        python3.x -m venv the-name-of-venv
        source the/path/of/venv/bin/activate
        pip install xxx -i https://pypi.tuna.tsinghua.edu.cn/simple
        deactivate

    可以使用 sudo pacman -Qdt 来查找孤包.
    可以使用 paccache -ruk0 来清除未安装的包缓存
    可以使用 paccache -r 来清除三个版本之前的包缓存
    可以使用 sudo pkgfile -u 来更新 pkgfile 的数据
    可以使用 sudo updatedb 来更新 locate 使用的索引数据
===============================================================
'''

print(help_list)
